### ISSUE TITLE
Move to RustCrypto/PAKEs?

### ISSUE THREAD

**Issue by newpavlov** [warner/spake2.rs#4]
RustCrypto already has [SRP](https://github.com/RustCrypto/PAKEs) implementation and SPAKE2 will be a good addition! I can give you admin access to the repo (same as with KDFs) if you want.

**Comment by warner** [comment]
Yeah, sounds good to me.

**Comment by newpavlov** [comment]
I've added you to the team with admin access! Feel free to create a PR or push directly!

**Comment by warner** [comment]
Started in https://github.com/RustCrypto/PAKEs/pull/3

**Comment by warner** [comment]
Done. This repository is now empty.
